/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as CasesCamileMendoncaRouteImport } from './routes/cases.camile-mendonca'
import { Route as CasesClinicaSimioniRouteImport } from './routes/cases.clinica-simioni'
import { Route as CasesDraCamileRouteImport } from './routes/cases.dra-camile'
import { Route as CasesDraCamileMendoncaRouteImport } from './routes/cases.dra-camile-mendonca'
import { Route as CasesDraCamilleMendoncaRouteImport } from './routes/cases.dra-camille-mendonca'
import { Route as CasesDraGiseliElianeRouteImport } from './routes/cases.dra-giseli-eliane'
import { Route as CasesPsOdontologiaRouteImport } from './routes/cases.ps-odontologia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCamileMendoncaRoute = CasesCamileMendoncaRouteImport.update({
  id: '/cases/camile-mendonca',
  path: '/cases/camile-mendonca',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesClinicaSimioniRoute = CasesClinicaSimioniRouteImport.update({
  id: '/cases/clinica-simioni',
  path: '/cases/clinica-simioni',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesDraCamileRoute = CasesDraCamileRouteImport.update({
  id: '/cases/dra-camile',
  path: '/cases/dra-camile',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesDraCamileMendoncaRoute = CasesDraCamileMendoncaRouteImport.update({
  id: '/cases/dra-camile-mendonca',
  path: '/cases/dra-camile-mendonca',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesDraCamilleMendoncaRoute = CasesDraCamilleMendoncaRouteImport.update({
  id: '/cases/dra-camille-mendonca',
  path: '/cases/dra-camille-mendonca',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesDraGiseliElianeRoute = CasesDraGiseliElianeRouteImport.update({
  id: '/cases/dra-giseli-eliane',
  path: '/cases/dra-giseli-eliane',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesPsOdontologiaRoute = CasesPsOdontologiaRouteImport.update({
  id: '/cases/ps-odontologia',
  path: '/cases/ps-odontologia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/cases/camile-mendonca': typeof CasesCamileMendoncaRoute
  '/cases/clinica-simioni': typeof CasesClinicaSimioniRoute
  '/cases/dra-camile': typeof CasesDraCamileRoute
  '/cases/dra-camile-mendonca': typeof CasesDraCamileMendoncaRoute
  '/cases/dra-camille-mendonca': typeof CasesDraCamilleMendoncaRoute
  '/cases/dra-giseli-eliane': typeof CasesDraGiseliElianeRoute
  '/cases/ps-odontologia': typeof CasesPsOdontologiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/cases/camile-mendonca': typeof CasesCamileMendoncaRoute
  '/cases/clinica-simioni': typeof CasesClinicaSimioniRoute
  '/cases/dra-camile': typeof CasesDraCamileRoute
  '/cases/dra-camile-mendonca': typeof CasesDraCamileMendoncaRoute
  '/cases/dra-camille-mendonca': typeof CasesDraCamilleMendoncaRoute
  '/cases/dra-giseli-eliane': typeof CasesDraGiseliElianeRoute
  '/cases/ps-odontologia': typeof CasesPsOdontologiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/cases/camile-mendonca': typeof CasesCamileMendoncaRoute
  '/cases/clinica-simioni': typeof CasesClinicaSimioniRoute
  '/cases/dra-camile': typeof CasesDraCamileRoute
  '/cases/dra-camile-mendonca': typeof CasesDraCamileMendoncaRoute
  '/cases/dra-camille-mendonca': typeof CasesDraCamilleMendoncaRoute
  '/cases/dra-giseli-eliane': typeof CasesDraGiseliElianeRoute
  '/cases/ps-odontologia': typeof CasesPsOdontologiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacidade'
    | '/termos'
    | '/cases/camile-mendonca'
    | '/cases/clinica-simioni'
    | '/cases/dra-camile'
    | '/cases/dra-camile-mendonca'
    | '/cases/dra-camille-mendonca'
    | '/cases/dra-giseli-eliane'
    | '/cases/ps-odontologia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacidade'
    | '/termos'
    | '/cases/camile-mendonca'
    | '/cases/clinica-simioni'
    | '/cases/dra-camile'
    | '/cases/dra-camile-mendonca'
    | '/cases/dra-camille-mendonca'
    | '/cases/dra-giseli-eliane'
    | '/cases/ps-odontologia'
  id:
    | '__root__'
    | '/'
    | '/privacidade'
    | '/termos'
    | '/cases/camile-mendonca'
    | '/cases/clinica-simioni'
    | '/cases/dra-camile'
    | '/cases/dra-camile-mendonca'
    | '/cases/dra-camille-mendonca'
    | '/cases/dra-giseli-eliane'
    | '/cases/ps-odontologia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  CasesCamileMendoncaRoute: typeof CasesCamileMendoncaRoute
  CasesClinicaSimioniRoute: typeof CasesClinicaSimioniRoute
  CasesDraCamileRoute: typeof CasesDraCamileRoute
  CasesDraCamileMendoncaRoute: typeof CasesDraCamileMendoncaRoute
  CasesDraCamilleMendoncaRoute: typeof CasesDraCamilleMendoncaRoute
  CasesDraGiseliElianeRoute: typeof CasesDraGiseliElianeRoute
  CasesPsOdontologiaRoute: typeof CasesPsOdontologiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/camile-mendonca': {
      id: '/cases/camile-mendonca'
      path: '/cases/camile-mendonca'
      fullPath: '/cases/camile-mendonca'
      preLoaderRoute: typeof CasesCamileMendoncaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/clinica-simioni': {
      id: '/cases/clinica-simioni'
      path: '/cases/clinica-simioni'
      fullPath: '/cases/clinica-simioni'
      preLoaderRoute: typeof CasesClinicaSimioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/dra-camile': {
      id: '/cases/dra-camile'
      path: '/cases/dra-camile'
      fullPath: '/cases/dra-camile'
      preLoaderRoute: typeof CasesDraCamileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/dra-camile-mendonca': {
      id: '/cases/dra-camile-mendonca'
      path: '/cases/dra-camile-mendonca'
      fullPath: '/cases/dra-camile-mendonca'
      preLoaderRoute: typeof CasesDraCamileMendoncaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/dra-camille-mendonca': {
      id: '/cases/dra-camille-mendonca'
      path: '/cases/dra-camille-mendonca'
      fullPath: '/cases/dra-camille-mendonca'
      preLoaderRoute: typeof CasesDraCamilleMendoncaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/dra-giseli-eliane': {
      id: '/cases/dra-giseli-eliane'
      path: '/cases/dra-giseli-eliane'
      fullPath: '/cases/dra-giseli-eliane'
      preLoaderRoute: typeof CasesDraGiseliElianeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/ps-odontologia': {
      id: '/cases/ps-odontologia'
      path: '/cases/ps-odontologia'
      fullPath: '/cases/ps-odontologia'
      preLoaderRoute: typeof CasesPsOdontologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  CasesCamileMendoncaRoute: CasesCamileMendoncaRoute,
  CasesClinicaSimioniRoute: CasesClinicaSimioniRoute,
  CasesDraCamileRoute: CasesDraCamileRoute,
  CasesDraCamileMendoncaRoute: CasesDraCamileMendoncaRoute,
  CasesDraCamilleMendoncaRoute: CasesDraCamilleMendoncaRoute,
  CasesDraGiseliElianeRoute: CasesDraGiseliElianeRoute,
  CasesPsOdontologiaRoute: CasesPsOdontologiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
